### ISSUE TITLE
Please add support for defaultuseraccount on macOS

### ISSUE THREAD

**Issue by call** [GoogleCloudPlatform/puppet-google-auth#1]
It would be great if this module understood how to load gcloud default user creds on macOS. If a user can begin playing with the google-cloud modules on their Mac workstation using ```puppet apply```, without having to generate a service account, if would make it quicker and easier to discover the value of these modules. 

Default user credentials don't live at this same path on macOS; I assume they are now stored in ```~/.config/gcloud/credentials.db```. Using Google Cloud SDK v180.0.1.
https://github.com/GoogleCloudPlatform/puppet-google-auth/blob/fd42778b9745daf7cc0362a94cad81c6fdc2ae85/lib/google/authorization.rb#L121-L122

**Comment by nelsonjr** [comment]
The `credentials.db` is now encoded using SQLite3 and attempting to support it would require all installations to have sqlite3 packages installed.

Instead we'll be adding support for `application-default` authentication mechanism and deprecating the `defaultuseraccount`. That aligns with how applications are supposed to take dependencies on Google Cloud SDK (as credentials.db is an internal gcloud resource and can change at any time).

A change that implements these new features is coming out soon.

**Comment by cyberious** [comment]
Hey @nelsonjr , has this been resolved or still a thing?

**Comment by call** [comment]
Still a thing. Hi @cyberious 👋
